using System.Globalization;
using System.Text;

namespace JourneyGen;

/// <summary>
/// Rewrites the block between the JOURNEY markers in README.MD.
/// Everything outside the markers is left exactly as you wrote it.
/// </summary>
public static class ReadmeWriter
{
    public const string Start = "<!-- JOURNEY:START -->";
    public const string End = "<!-- JOURNEY:END -->";

    public static string Render(JourneyConfig cfg, CodeAnalyzer analyzer, GitSummary git, Provenance prov, string? siteUrl)
    {
        var done = cfg.Concepts.Count(c => c.Done);
        var total = cfg.Concepts.Count;
        var pct = total == 0 ? 0 : (int)Math.Round(100.0 * done / total);

        var sb = new StringBuilder();
        sb.AppendLine(Start);
        sb.AppendLine("<!-- Generated by tools/JourneyGen. Do not edit by hand: your changes will be overwritten. -->");
        sb.AppendLine();
        sb.AppendLine($"## {cfg.Title}");
        sb.AppendLine();
        if (cfg.Tagline.Length > 0) { sb.AppendLine($"_{cfg.Tagline}_"); sb.AppendLine(); }

        sb.Append(Badge("concepts", $"{done} of {total}", "512BD4")).Append(' ');
        sb.Append(Badge("C# files", analyzer.SourceFiles.Count.ToString(CultureInfo.InvariantCulture), "0078D4")).Append(' ');
        sb.Append(Badge("lines", analyzer.TotalLines.ToString(CultureInfo.InvariantCulture), "0078D4")).Append(' ');
        sb.Append(Badge("types", analyzer.Types.Count.ToString(CultureInfo.InvariantCulture), "0078D4")).Append(' ');
        sb.Append(Badge("commits", git.TotalCommits.ToString(CultureInfo.InvariantCulture), "555555"));
        if (prov.Available)
            sb.Append(' ').Append(Badge("app code by me", prov.App.YouPercent + "%", "1BAF7A"));
        sb.AppendLine();
        sb.AppendLine();

        sb.AppendLine($"**Progress** `{Bar(pct)}` **{pct}%**");
        sb.AppendLine();
        if (git.TotalCommits > 0)
            sb.AppendLine($"Started {git.FirstCommit} · last commit {git.LastCommit} · {git.ActiveDays} active days");
        if (siteUrl is { Length: > 0 })
        {
            sb.AppendLine();
            sb.AppendLine($"📊 **[Full dashboard with charts and timeline]({siteUrl})**");
        }
        sb.AppendLine();

        if (cfg.Assignment.Items.Count > 0) AppendAssignment(sb, cfg.Assignment);

        sb.AppendLine("### Domain model");
        sb.AppendLine();
        sb.AppendLine("_Generated from the source on every push — this diagram cannot drift from the code._");
        sb.AppendLine();
        sb.AppendLine("```mermaid");
        sb.AppendLine(MermaidRenderer.ClassDiagram(analyzer.Types, cfg.Diagram));
        sb.AppendLine("```");
        sb.AppendLine();

        sb.AppendLine("### Projects");
        sb.AppendLine();
        sb.AppendLine("| Project | Files | Lines | Types |");
        sb.AppendLine("|---|---:|---:|---:|");
        foreach (var p in analyzer.Projects)
            sb.AppendLine($"| `{p.Name}` | {p.Files} | {p.Lines} | {p.Types} |");
        sb.AppendLine();

        if (prov.Available) AppendProvenance(sb, prov);

        if (cfg.Roadmap.Areas.Count > 0) AppendRoadmap(sb, cfg.Roadmap);

        sb.AppendLine("### Concepts covered");
        sb.AppendLine();
        foreach (var area in cfg.Concepts.GroupBy(c => c.Area))
        {
            var areaDone = area.Count(c => c.Done);
            sb.AppendLine($"<details{(areaDone > 0 ? " open" : "")}>");
            sb.AppendLine($"<summary><b>{Escape(area.Key)}</b> — {areaDone}/{area.Count()}</summary>");
            sb.AppendLine();
            foreach (var c in area)
            {
                var box = c.Done ? "[x]" : "[ ]";
                var label = c.Done ? $"**{Escape(c.Label)}**" : Escape(c.Label);
                var note = c.Notes.Length > 0 ? $" — {Escape(c.Notes)}" : "";
                var where = c.Done && c.Evidence.Count > 0
                    ? $" <sub>`{c.Evidence[0]}`{(c.Evidence.Count > 1 ? $" +{c.Evidence.Count - 1}" : "")}</sub>"
                    : c.Planned ? " <sub>planned</sub>" : "";
                sb.AppendLine($"- {box} {label}{note}{where}");
            }
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }

        sb.AppendLine($"<sub>Last updated {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC</sub>");
        sb.AppendLine();
        sb.Append(End);
        return sb.ToString();
    }

    static void AppendRoadmap(StringBuilder sb, Roadmap r)
    {
        sb.AppendLine($"### {Escape(r.Title)}");
        sb.AppendLine();
        if (r.Source.Length > 0) { sb.AppendLine($"_{Escape(r.Source)}._"); sb.AppendLine(); }

        sb.AppendLine($"`{Bar(r.Percent)}` **{r.Done} of {r.Total} covered** across {r.Areas.Count} areas");
        sb.AppendLine();
        if (r.Note.Length > 0) { sb.AppendLine($"<sub>{Escape(r.Note)}</sub>"); sb.AppendLine(); }

        sb.AppendLine("| Area | Covered | |");
        sb.AppendLine("|---|---:|---|");
        foreach (var a in r.Areas)
            sb.AppendLine($"| {Escape(a.Name)} | {a.Done}/{a.Items.Count} | `{Bar(a.Percent)}` {a.Percent}% |");
        sb.AppendLine();

        foreach (var a in r.Areas)
        {
            sb.AppendLine("<details>");
            sb.AppendLine($"<summary><b>{Escape(a.Name)}</b> — {a.Done}/{a.Items.Count}" +
                          (a.Summary.Length > 0 ? $" · <sub>{Escape(a.Summary)}</sub>" : "") + "</summary>");
            sb.AppendLine();
            foreach (var i in a.Items)
            {
                var st = i.EffectiveStatus;
                var box = st == "done" ? "[x]" : "[ ]";
                var label = st == "done" ? $"**{Escape(i.Label)}**" : Escape(i.Label);
                var tail = st switch
                {
                    "done" when i.Evidence.Count > 0 => $" <sub>`{i.Evidence[0]}`{(i.Evidence.Count > 1 ? $" +{i.Evidence.Count - 1}" : "")}</sub>",
                    "in-progress" => " <sub>in progress</sub>",
                    _ when !i.CodeDetectable => " <sub>judgement — not code-detectable</sub>",
                    _ => "",
                };
                var note = i.Notes.Length > 0 ? $" — {Escape(i.Notes)}" : "";
                sb.AppendLine($"- {box} {label}{note}{tail}");
            }
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    static void AppendAssignment(StringBuilder sb, Assignment a)
    {
        sb.AppendLine($"### {Escape(a.Title)}");
        sb.AppendLine();

        var meta = new List<string>();
        if (a.Source.Length > 0) meta.Add(Escape(a.Source));
        if (a.AssignedOn.Length > 0) meta.Add($"assigned {a.AssignedOn}");
        if (a.ReviewOn.Length > 0)
        {
            var days = a.DaysToReview;
            meta.Add(days is null
                ? $"next review {a.ReviewOn}"
                : $"next review **{a.ReviewOn}** ({(days == 0 ? "today" : days == 1 ? "in 1 day" : $"in {days} days")})");
        }
        if (meta.Count > 0) { sb.AppendLine(string.Join(" · ", meta)); sb.AppendLine(); }

        sb.AppendLine($"`{Bar(a.DonePercent)}` **{a.Done} of {a.Items.Count} complete** " +
                      $"· {a.InProgress} in progress" + (a.NotStarted > 0 ? $" · {a.NotStarted} not started" : ""));
        sb.AppendLine();

        sb.AppendLine("| Item | Status | Evidence in the code |");
        sb.AppendLine("|---|---|---|");
        foreach (var i in a.Items)
            sb.AppendLine($"| {Escape(i.Label)}{(i.Notes.Length > 0 ? $"<br><sub>{Escape(i.Notes)}</sub>" : "")} " +
                          $"| {StatusLabel(i)} | {EvidenceCell(i)} |");
        sb.AppendLine();

        var shaky = a.Items.Where(i => i.Unevidenced || i.PartiallyEvidenced).ToList();
        if (shaky.Count > 0)
        {
            sb.AppendLine("> **Marked complete, but the code does not fully show it yet:** " +
                          string.Join(", ", shaky.Select(i => Escape(i.Label))) + ".");
            sb.AppendLine("> Status above is my own; the evidence column is generated from the source, so the two can disagree.");
            sb.AppendLine();
        }
    }

    static string StatusLabel(AssignmentItem i) => i.Status switch
    {
        "done" => "✅ Completed",
        "in-progress" => "🔄 In progress",
        _ => "⬜ Not started",
    };

    static string EvidenceCell(AssignmentItem i)
    {
        if (i.Parts.Count > 0)
            return string.Join("<br>", i.Parts.Select(p =>
                $"{(p.Detected ? "✓" : "✗")} `{Escape(p.Label)}`" +
                (p.Detected && p.Evidence.Count > 0 ? $" <sub>{p.Evidence[0]}</sub>" : "")));

        if (!i.Detected) return "_none yet_";
        var first = i.Evidence.Count > 0 ? $"`{i.Evidence[0]}`" : "found";
        return first + (i.Evidence.Count > 1 ? $" <sub>+{i.Evidence.Count - 1}</sub>" : "");
    }

    static void AppendProvenance(StringBuilder sb, Provenance prov)
    {
        var app = prov.App;
        var tooling = prov.Tooling;

        sb.AppendLine("### Who wrote this code");
        sb.AppendLine();
        sb.AppendLine($"**{app.YouPercent}% of the application code is mine** — {app.You} of the {app.Authored} " +
                      "lines in it that anyone authored by hand.");
        if (app.Scaffold > 0)
            sb.AppendLine($"A further {app.Scaffold} lines are `dotnet new` template output, which neither I nor an AI wrote.");
        sb.AppendLine();
        sb.AppendLine("| Project | Mine | AI | Scaffold | Share authored by me |");
        sb.AppendLine("|---|---:|---:|---:|---|");

        foreach (var p in prov.Projects.Where(p => !p.IsTooling))
        {
            var share = p.Authored == 0 ? "— _template output only_" : $"`{Bar(p.YouPercent)}` {p.YouPercent}%";
            sb.AppendLine($"| `{p.Project}` | {p.You} | {p.Ai} | {p.Scaffold} | {share} |");
        }
        sb.AppendLine($"| **Application total** | **{app.You}** | **{app.Ai}** | **{app.Scaffold}** | `{Bar(app.YouPercent)}` **{app.YouPercent}%** |");
        sb.AppendLine();

        sb.AppendLine("<details>");
        sb.AppendLine("<summary>How this is measured, and what is declared</summary>");
        sb.AppendLine();
        sb.AppendLine("Every non-blank line is attributed with `git blame` to the commit that last touched it,");
        sb.AppendLine("and each commit is classified once. Lines count as mine by default — a line is only");
        sb.AppendLine("AI or scaffold because a rule in `journey.json` says so. Edit a scaffold line and blame");
        sb.AppendLine("reassigns it to me automatically, so the split cannot drift from the code.");
        sb.AppendLine();
        sb.AppendLine("Going forward this is automatic: any commit whose message carries an AI trailer");
        sb.AppendLine("(`Co-Authored-By: Claude`, `Assisted-By: Claude`) has its lines counted as AI-written.");
        sb.AppendLine();
        if (tooling.Total > 0)
        {
            sb.AppendLine($"The tooling that builds this page is a further {tooling.Total} lines, " +
                          $"**{tooling.AiPercent}% AI-written** — `tools/JourneyGen`, the generator and its");
            sb.AppendLine("page template. It is kept out of the figures above rather than averaged into them,");
            sb.AppendLine("since it generates the page and is not part of the application.");
            sb.AppendLine();
            sb.AppendLine("| Tooling | Mine | AI | Share written by AI |");
            sb.AppendLine("|---|---:|---:|---|");
            foreach (var p in prov.Projects.Where(p => p.IsTooling))
                sb.AppendLine($"| `{p.Project}` | {p.You} | {p.Ai} | `{Bar(p.AiPercent)}` {p.AiPercent}% |");
            sb.AppendLine();
        }

        sb.AppendLine("Commits counted as anything other than my own hand:");
        sb.AppendLine();
        sb.AppendLine("| Commit | Counted as | Subject |");
        sb.AppendLine("|---|---|---|");
        foreach (var (sha, subject, source) in prov.Declared.Take(20))
            sb.AppendLine($"| `{sha}` | {(source == Provenance.Source.Ai ? "AI" : "scaffold")} | {Escape(Trim(subject, 64))} |");
        sb.AppendLine();
        sb.AppendLine("</details>");
        sb.AppendLine();
    }

    static string Trim(string s, int max) => s.Length <= max ? s : s[..(max - 1)] + "…";

    public static string Inject(string readme, string block)
    {
        var s = readme.IndexOf(Start, StringComparison.Ordinal);
        var e = readme.IndexOf(End, StringComparison.Ordinal);

        if (s >= 0 && e > s)
            return readme[..s] + block + readme[(e + End.Length)..];

        // First run: append the block and leave any hand-written content above it.
        return readme.TrimEnd() + "\n\n---\n\n" + block + "\n";
    }

    static string Bar(int pct)
    {
        const int width = 20;
        var filled = (int)Math.Round(width * pct / 100.0);
        return new string('█', filled) + new string('░', width - filled);
    }

    static string Badge(string label, string value, string color)
    {
        static string Enc(string s) => Uri.EscapeDataString(s.Replace("-", "--").Replace("_", "__")).Replace("%20", "_");
        return $"![{label}](https://img.shields.io/badge/{Enc(label)}-{Enc(value)}-{color})";
    }

    static string Escape(string s) => s.Replace("|", "\\|");
}
