using System.Globalization;
using System.Text;

namespace JourneyGen;

/// <summary>
/// Rewrites the block between the JOURNEY markers in README.MD.
/// Everything outside the markers is left exactly as you wrote it.
/// </summary>
public static class ReadmeWriter
{
    public const string Start = "<!-- JOURNEY:START -->";
    public const string End = "<!-- JOURNEY:END -->";

    public static string Render(JourneyConfig cfg, CodeAnalyzer analyzer, GitSummary git, string? siteUrl)
    {
        var done = cfg.Concepts.Count(c => c.Done);
        var total = cfg.Concepts.Count;
        var pct = total == 0 ? 0 : (int)Math.Round(100.0 * done / total);

        var sb = new StringBuilder();
        sb.AppendLine(Start);
        sb.AppendLine("<!-- Generated by tools/JourneyGen. Do not edit by hand: your changes will be overwritten. -->");
        sb.AppendLine();
        sb.AppendLine($"## {cfg.Title}");
        sb.AppendLine();
        if (cfg.Tagline.Length > 0) { sb.AppendLine($"_{cfg.Tagline}_"); sb.AppendLine(); }

        sb.Append(Badge("concepts", $"{done} of {total}", "512BD4")).Append(' ');
        sb.Append(Badge("C# files", analyzer.SourceFiles.Count.ToString(CultureInfo.InvariantCulture), "0078D4")).Append(' ');
        sb.Append(Badge("lines", analyzer.TotalLines.ToString(CultureInfo.InvariantCulture), "0078D4")).Append(' ');
        sb.Append(Badge("types", analyzer.Types.Count.ToString(CultureInfo.InvariantCulture), "0078D4")).Append(' ');
        sb.Append(Badge("commits", git.TotalCommits.ToString(CultureInfo.InvariantCulture), "555555"));
        sb.AppendLine();
        sb.AppendLine();

        sb.AppendLine($"**Progress** `{Bar(pct)}` **{pct}%**");
        sb.AppendLine();
        if (git.TotalCommits > 0)
            sb.AppendLine($"Started {git.FirstCommit} · last commit {git.LastCommit} · {git.ActiveDays} active days");
        if (siteUrl is { Length: > 0 })
        {
            sb.AppendLine();
            sb.AppendLine($"📊 **[Full dashboard with charts and timeline]({siteUrl})**");
        }
        sb.AppendLine();

        sb.AppendLine("### Domain model");
        sb.AppendLine();
        sb.AppendLine("_Generated from the source on every push — this diagram cannot drift from the code._");
        sb.AppendLine();
        sb.AppendLine("```mermaid");
        sb.AppendLine(MermaidRenderer.ClassDiagram(analyzer.Types, cfg.Diagram));
        sb.AppendLine("```");
        sb.AppendLine();

        sb.AppendLine("### Projects");
        sb.AppendLine();
        sb.AppendLine("| Project | Files | Lines | Types |");
        sb.AppendLine("|---|---:|---:|---:|");
        foreach (var p in analyzer.Projects)
            sb.AppendLine($"| `{p.Name}` | {p.Files} | {p.Lines} | {p.Types} |");
        sb.AppendLine();

        sb.AppendLine("### Concepts covered");
        sb.AppendLine();
        foreach (var area in cfg.Concepts.GroupBy(c => c.Area))
        {
            var areaDone = area.Count(c => c.Done);
            sb.AppendLine($"<details{(areaDone > 0 ? " open" : "")}>");
            sb.AppendLine($"<summary><b>{Escape(area.Key)}</b> — {areaDone}/{area.Count()}</summary>");
            sb.AppendLine();
            foreach (var c in area)
            {
                var box = c.Done ? "[x]" : "[ ]";
                var label = c.Done ? $"**{Escape(c.Label)}**" : Escape(c.Label);
                var note = c.Notes.Length > 0 ? $" — {Escape(c.Notes)}" : "";
                var where = c.Done && c.Evidence.Count > 0
                    ? $" <sub>`{c.Evidence[0]}`{(c.Evidence.Count > 1 ? $" +{c.Evidence.Count - 1}" : "")}</sub>"
                    : c.Planned ? " <sub>planned</sub>" : "";
                sb.AppendLine($"- {box} {label}{note}{where}");
            }
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }

        sb.AppendLine($"<sub>Last updated {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC</sub>");
        sb.AppendLine();
        sb.Append(End);
        return sb.ToString();
    }

    public static string Inject(string readme, string block)
    {
        var s = readme.IndexOf(Start, StringComparison.Ordinal);
        var e = readme.IndexOf(End, StringComparison.Ordinal);

        if (s >= 0 && e > s)
            return readme[..s] + block + readme[(e + End.Length)..];

        // First run: append the block and leave any hand-written content above it.
        return readme.TrimEnd() + "\n\n---\n\n" + block + "\n";
    }

    static string Bar(int pct)
    {
        const int width = 20;
        var filled = (int)Math.Round(width * pct / 100.0);
        return new string('█', filled) + new string('░', width - filled);
    }

    static string Badge(string label, string value, string color)
    {
        static string Enc(string s) => Uri.EscapeDataString(s.Replace("-", "--").Replace("_", "__")).Replace("%20", "_");
        return $"![{label}](https://img.shields.io/badge/{Enc(label)}-{Enc(value)}-{color})";
    }

    static string Escape(string s) => s.Replace("|", "\\|");
}
